hash-format = "sha256"

[[files]]
file = "mods/abnormals-delight.pw.toml"
hash = "de8c3546c0385ff9bdf997d3137b7ed19da929e2931bdca5d287a269f2c343a5"
metafile = true

[[files]]
file = "mods/accessories-compat-layer.pw.toml"
hash = "9f3abbba0805d021f4fec52693732de1c098ab6049f6065b9be494e9c339eeee"
metafile = true

[[files]]
file = "mods/accessories.pw.toml"
hash = "5b786ab7a57e37ec4b8f888157f79608e871653fc4b6a8cba0296690fe863704"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "6d3a1c92eee4dd671253c41ec000ae48064a33c45263d6adce5cad466395169d"
metafile = true

[[files]]
file = "mods/ars-nouveau.pw.toml"
hash = "d2b8dc640bd23696953262d883382f299ae002968ce4a8c7ed6d39c706b350de"
metafile = true

[[files]]
file = "mods/arsdelight.pw.toml"
hash = "4cb216ce5180c707ea38e47de43cbda4a927a4a0534d325d1cb8a72f7e529072"
metafile = true

[[files]]
file = "mods/artifacts.pw.toml"
hash = "730498992eb3dad74a9bf9d9cd0cc104e4e205230bf76851f605c2d1a2b16bff"
metafile = true

[[files]]
file = "mods/atmospheric.pw.toml"
hash = "af6c0039538f5f5387184e6d055d5b5afe5f58de42ab451271d69e810d09eefb"
metafile = true

[[files]]
file = "mods/autumnity.pw.toml"
hash = "4b272e27bc83062b9e5af6c597b002bad58088f1aba0f14736f30ca37c40d959"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
hash = "95322b6e88dbeba91b5e7a30d6bd011629124ae8aef5bf1b7d1304f12bd4619c"
metafile = true

[[files]]
file = "mods/berry-good.pw.toml"
hash = "093abe6db61cc854c7bcd46a3e0bec69fb03af507a8afcc3fdf25e1a58aa6aa6"
metafile = true

[[files]]
file = "mods/blueprint.pw.toml"
hash = "a5122c5ecc0e36da4f60474cc8ecaff590aaeae8be545ffddfe2c25db89816e7"
metafile = true

[[files]]
file = "mods/boatload.pw.toml"
hash = "3e4ef8a1b4a51f845e60751b2431cc599aa52b6a43a79dacaa5fc7aadc15fe1c"
metafile = true

[[files]]
file = "mods/bridging-mod.pw.toml"
hash = "c50696cd98b02ba03425574c7850443f5cba8e097af4b6ae1c8b42bd5316a8eb"
metafile = true

[[files]]
file = "mods/buzzier-bees.pw.toml"
hash = "3a59ca21bc4e6e179ce53231b0a7bb56a2ca5f8304500f9ee202e476b1a4e719"
metafile = true

[[files]]
file = "mods/cardiac.pw.toml"
hash = "46e270352c265c328b122ac960a3478e1e3739c7e791b52139466551435d5bcc"
metafile = true

[[files]]
file = "mods/clavis.pw.toml"
hash = "5fc14d5c2ee41f46f20d997893e8df8ccafbfe9b6460bf6e11bd6c3d6025a295"
metafile = true

[[files]]
file = "mods/clayworks.pw.toml"
hash = "055b1cba862cdddfce8466ce63b9cf1bf07541602069e80c6cf9f50d64ec8197"
metafile = true

[[files]]
file = "mods/connector.pw.toml"
hash = "aa242da373359065cb62d8e1094e2f17b456f3ea300db145896cf6c6aae43101"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "2e082857985c7550efdad38a1997b9805051b07fb61b0cd30921e786a8521130"
metafile = true

[[files]]
file = "mods/cooking-for-blockheads.pw.toml"
hash = "d7e6f009549d3862ec0f285aa81be1d0544fe618adc3011454bcbd2626d6a98f"
metafile = true

[[files]]
file = "mods/craftpresence.pw.toml"
hash = "feb859385e0320c6a3a452d175885d138f567c938f7f3fc3558bdec17e0241ae"
metafile = true

[[files]]
file = "mods/create.pw.toml"
hash = "d6043c928c34ce1f4ada544a49193f95c281665cf88d4931e73370ea02870bed"
metafile = true

[[files]]
file = "mods/cull-leaves.pw.toml"
hash = "a9b9623c952949837c1c6827b94b5969241c44825483a901cad12fcda12d40e9"
metafile = true

[[files]]
file = "mods/curios.pw.toml"
hash = "36debf7653e95a855b4fedacc19027cf2e01960fc0b6d55ef2ffbffbcb455690"
metafile = true

[[files]]
file = "mods/dnt-ancient-city-overhaul.pw.toml"
hash = "58096a477ce5489d4c283d910b0e8b285c6fea7ed8dd9010136f6af9464cc6e9"
metafile = true

[[files]]
file = "mods/dnt-desert-temple-overhaul.pw.toml"
hash = "f7c82a9de37ed0416e9b9ff33ccb92159a10b85d5a0ec61781f4b634a921f6ba"
metafile = true

[[files]]
file = "mods/dnt-jungle-temple-overhaul.pw.toml"
hash = "d32fd96a06d0f708e4c613d10c700e1f42402c32d239c2d07578600a71ee649e"
metafile = true

[[files]]
file = "mods/dnt-nether-fortress-overhaul.pw.toml"
hash = "25d0d7bb1e7d5999402150afd965e6f5f8b6b9e5a94e2fadd95d5bc581a7ab11"
metafile = true

[[files]]
file = "mods/dnt-ocean-monument-overhaul.pw.toml"
hash = "0c45d8d12fe993224ea37b11e5ef2fbdf4b6560aaca7938217db0392a028ad3f"
metafile = true

[[files]]
file = "mods/dnt-pillager-outpost-overhaul.pw.toml"
hash = "64cb86049ceccbac91f9099f7913d163b8265aeabcbfb7c536f286077f7829e2"
metafile = true

[[files]]
file = "mods/dnt-stronghold-overhaul.pw.toml"
hash = "88901e62bd4c195ae07dc7b53bf54f52d1a330b0c84da0edd24e938d1022f8b1"
metafile = true

[[files]]
file = "mods/dnt-swamp-hut-overhaul.pw.toml"
hash = "d61eb0419dac47f5cca10b54edcc289775a18c51c2e7b0ed3bd90daee8ae59b2"
metafile = true

[[files]]
file = "mods/dnt-woodland-mansion-overhaul.pw.toml"
hash = "dabdd4071bef81076c7fe7ff6bfa85830f5d87efd25b069fb78eb7134304b567"
metafile = true

[[files]]
file = "mods/dungeons-and-taverns.pw.toml"
hash = "b9244dca740d333c22f3425991fdd2fd40d3ae12384079a40a6fb7d4bca18a18"
metafile = true

[[files]]
file = "mods/ears.pw.toml"
hash = "b42ea604c46fc73d9474ebc9d6d3d64a1efe6b9d5df8512c71a86f820eb8a105"
metafile = true

[[files]]
file = "mods/emi.pw.toml"
hash = "d3c9b48d7caa2ed964e5d1a4dab1da5655c63f0a7e4a59231c4369be7ffc30e1"
metafile = true

[[files]]
file = "mods/emixx.pw.toml"
hash = "1a2ca9865ee018d9cc28693cfa6aa5e181a636eef9fa7811564ce4b6b859ff9d"
metafile = true

[[files]]
file = "mods/every-compat.pw.toml"
hash = "a7fdceccef7bee99b5cf8075b4f80229ce14eab8c590935cec8056e5da6680eb"
metafile = true

[[files]]
file = "mods/extra-mod-integrations.pw.toml"
hash = "1c516c3cdedc1a2b6bdd4d7ab12469142d5ee9dadc03e815be3f2a04b95f7135"
metafile = true

[[files]]
file = "mods/farmers-delight.pw.toml"
hash = "44abae510395f12f9ea97b8296b2f72e25f18b9f3f2cc0ee42c0d9afd73fe0b3"
metafile = true

[[files]]
file = "mods/forgified-fabric-api.pw.toml"
hash = "ec1bd5b80399287ca33a113086bee9d5697b7e673c9f593e5a1aeca4c9bad4c9"
metafile = true

[[files]]
file = "mods/gallery.pw.toml"
hash = "abab6d2386547e55cc5efce1c0e64d1f18bb3ce106e2dd011693f70508da6751"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
hash = "960fb33c17aca9c635f99009c1f16d75c312d043e302a599f6ce8040452079e6"
metafile = true

[[files]]
file = "mods/immersive-ui.pw.toml"
hash = "4a5e7ba2003a7c5df99905c4952c43e011f7b29a7fad9e20457a76a72e92fde2"
metafile = true

[[files]]
file = "mods/incubation.pw.toml"
hash = "fa955af8034193ed9f5378b254bdbd07229088acc8e48ffd6b741c3093d22896"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "f67aa60c765593a8c70f78296a460349c6aef5f4a16d173eae02e8803b545ad4"
metafile = true

[[files]]
file = "mods/jade-addons-forge.pw.toml"
hash = "8cd8400cb4e2c5ba60c8a359a7b6ff501078d2056eab0aba7f6b0ac77b7a0694"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "e7d3f7e0472ba9a3ef946fa5defcb157e4126636e603c2306d4ad6065936d5e2"
metafile = true

[[files]]
file = "mods/kotlin-for-forge.pw.toml"
hash = "1a9ec5beaba1be3151b8710db2bfab90c2063a4dafaf2720336852245a145cc4"
metafile = true

[[files]]
file = "mods/l_enders-cataclysm.pw.toml"
hash = "0ba45c4cf0d0c605841b708a23417668e1ee4c9860a1d4572b122d6348c113ed"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
hash = "502d4ba2ca8c7f6f52830cfc43fc12b567023266f2b557ee2b8eea737b58f8ea"
metafile = true

[[files]]
file = "mods/lionfish-api.pw.toml"
hash = "3d5d4c97ece8d1470d785fbffb44c1f17ca406931d08dd0cfd5d77745a956979"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "7b8e8af83e8583adc91b2d859e5355f1bd0516a346d2584b8b01c004467d18af"
metafile = true

[[files]]
file = "mods/macaws-bridges.pw.toml"
hash = "c6887c071d6515a39aeb915429304ea9fdae876decde3ad66062c9ba779b16b4"
metafile = true

[[files]]
file = "mods/midnightlib.pw.toml"
hash = "3382daf9b5fadbbef742b84fe5b09fa912cc75cd4234e0ba573b85a513354123"
metafile = true

[[files]]
file = "mods/moonlight.pw.toml"
hash = "56f90779687daa9101ae4dc2730a3b44b07ed3a5113eb4f4b41e36143b297f56"
metafile = true

[[files]]
file = "mods/neapolitan.pw.toml"
hash = "e68a5fa89a2b2c17a3f807875c8f32b5f69d7c083a8c88e8f29f3832c9bb4385"
metafile = true

[[files]]
file = "mods/neat.pw.toml"
hash = "b7296f6d9061c1d7efbd8693c4463d5f2bf1450b0c289ac3297fdabf7ce99479"
metafile = true

[[files]]
file = "mods/no-telemetry.pw.toml"
hash = "ebd48452773a4b6b4b7dcedbfb71c8986ec97780fcce040542c8e8fd67f22c56"
metafile = true

[[files]]
file = "mods/notenoughrecipebook.pw.toml"
hash = "6df80014ec12832c5627e60f7c916e0cb8a9d8dbb3f7c4ff863de3a6e39957aa"
metafile = true

[[files]]
file = "mods/octo-lib.pw.toml"
hash = "a52c2b505827a549dfabebd6586591910fcf6e1a62dbb27604aacc96d412d5e4"
metafile = true

[[files]]
file = "mods/owo-lib.pw.toml"
hash = "46831c04077a06df823bcd0f254833a90a9a9ccc78f5069f4b4c27fa301ac0cf"
metafile = true

[[files]]
file = "mods/perception.pw.toml"
hash = "0151c79c4b39d79ad9343ba8d09d7c1722d44b3c056f9337837628628922335d"
metafile = true

[[files]]
file = "mods/personality!.pw.toml"
hash = "fd4c668a34df55aa670b1d3c0f3aba069f7902cc1631d266e6d9db3370ec3536"
metafile = true

[[files]]
file = "mods/platform.pw.toml"
hash = "1264a43ce919f188661443bd959cdebb4be04ce70a2965835043c2b18cae730e"
metafile = true

[[files]]
file = "mods/rar-compat.pw.toml"
hash = "68d7d2cbeb93c10f99b3985c96b098aed7dc64f5d08e4855fdd9f37a759f7072"
metafile = true

[[files]]
file = "mods/re-animal.pw.toml"
hash = "4a9d91d42c87524eb3971456987857dc86d30cafba2841c978c92e077107d3da"
metafile = true

[[files]]
file = "mods/relics-mod.pw.toml"
hash = "2214ea9951c660cf7adbb09e3402a2f70af3738a6f271fdad810a4a033da9c51"
metafile = true

[[files]]
file = "mods/reliquified-ars-nouveau.pw.toml"
hash = "2cba8e3227209edcb88307aa9cddfb6362dad9b9ab96596ad519913f8e60a196"
metafile = true

[[files]]
file = "mods/reliquified-l-ender-s-cataclysm.pw.toml"
hash = "0a11dfdd0fbfcdd535bc610fb2d9b9694eb13c40b757c4a686228d2b7da6fb5e"
metafile = true

[[files]]
file = "mods/reliquified-twilight-forest.pw.toml"
hash = "ea80cd43856df236cdfc3f5b2a826e2965eb83d4f35cf465ccbd61c4b5b02bf7"
metafile = true

[[files]]
file = "mods/searchables.pw.toml"
hash = "ce9ddada6ffd55a512149cc474c6a453281a997a5fdf1b7b4a2cc73f875e704a"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "0281ed9713f3141bdac363056a791845510e14761ea65b4b2813cf96d664b20a"
metafile = true

[[files]]
file = "mods/sophisticated-backpacks-create-integration.pw.toml"
hash = "98894c50922dfad36e4313d798d4497a61c42ce855b44fd63aea79b4990cac5d"
metafile = true

[[files]]
file = "mods/sophisticated-backpacks.pw.toml"
hash = "afc8b791ae5751382ecb3715fef8a7a50059cc120c5ae556ed7967a97984a1dd"
metafile = true

[[files]]
file = "mods/sophisticated-core.pw.toml"
hash = "0c0d7d7785e4ceea16c3ed1c9905bdf33532de1e290b147323c079515f2dc04b"
metafile = true

[[files]]
file = "mods/sophisticated-sorter.pw.toml"
hash = "43364881676d63a48371f0f40c112ed3159c027a2f5f159980c8a7c620c394db"
metafile = true

[[files]]
file = "mods/sophisticated-storage-create-integration.pw.toml"
hash = "e6bb3eeda43411c95fa84549ba3281df62654e36140ec322190206fc8df512a4"
metafile = true

[[files]]
file = "mods/sophisticated-storage.pw.toml"
hash = "007d2d5934cd538ab80fcbb70f2737dd14e9f4057f3424fa14e41a761ef6b7f7"
metafile = true

[[files]]
file = "mods/the-twilight-forest.pw.toml"
hash = "bbd1d4b8b1562f98c9247a29de80b0ba5447dda5b549a8b4ee732c38925b784b"
metafile = true

[[files]]
file = "mods/tmrv.pw.toml"
hash = "9a2c112447329f1daea6cda77d68d3cdf7f292ae9e72f69adbfc18cb18ab1eeb"
metafile = true

[[files]]
file = "mods/unilib.pw.toml"
hash = "ad155d9399b4a32e64770845f5561f996bde246ccc5eaf47fb5909e3114a7a13"
metafile = true

[[files]]
file = "mods/upgrade-aquatic.pw.toml"
hash = "c5ca24c184e37a29d5c6f1d244f0fd80e0f615723d35b4d0e04bcbd97d9bb8e4"
metafile = true

[[files]]
file = "mods/vanillabackport.pw.toml"
hash = "b278c479cc1d50ffbcf27e3514bcdb0995471eb11e2335c54255edc459b3462e"
metafile = true

[[files]]
file = "mods/woodworks.pw.toml"
hash = "c528ce61fc0e0036a7b6055ad71b1a5bf1cb388537397b6852464b9855d69345"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "9a89a97f142873b9ab62d2c7c807ac22e6f16c828282052b416a6f3f7f785a48"
metafile = true

[[files]]
file = "mods/yungs-api.pw.toml"
hash = "d9c0c9209bac0b693af2a7c1e47ffb28d366bad19c91df31dc6d345fa75250a1"
metafile = true

[[files]]
file = "mods/yungs-bridges.pw.toml"
hash = "9d9b074b2425fc4f19808b7d6df4a0baeae39a37e909107aaa85004df1a2d195"
metafile = true
