name = "Packwiz"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "63b8f679479d8b84773c373c22ec0321a64621f782641605b57217c30befcee1"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.216"
