name = "Packwiz"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "324a7dac96da837f6af4982e084b6f2e46d6fe16a42a066548759d25e8445a68"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.216"
