name = "Packwiz"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7329d57ea63df4e6a6ae179c134c1d5ef00ceaca344094bb2c03a76b05a99969"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.216"
