name = "Packwiz"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0ee63665006af5b15f1c054710038545661cc06a0864972cd4c8a7a97639414f"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.216"
