name = "Packwiz"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d41712f209c3247f2d0d347e8789b34167556537a5021d8cc1cb76260e5320bd"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.216"
