name = "Packwiz"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1cac017385825dc5e810440a5c628fd8e254b7024064024cb08e794efa2af6e9"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.216"
