name = "Packwiz"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e51ce5356ec29ed02efc2dff3275e9466d5610da9d442030dfaa96a8d466cf43"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.216"
