name = "Packwiz"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c86c1769fb6227171c807309287488481e363b6106c5bb65c3ab23e7b29f6dd5"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.216"
