name = "Packwiz"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f08cd595c296afebb3e27cf191654ae2b452abf559bbc95b6c6de38fa7849757"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.216"
